McCulloch-Pitts Neural Model for AND case

Step 1: Generate a vector of inputs and a vector of weights.

In [48]:
import numpy as np

input_table = np.array([
 [0,0,0],
 [0,1,0],
 [1,0,1],
 [1,1,1]
])
print(f'Input Table:\n{input_table}')


Input Table:
[[0 0 0]
 [0 1 0]
 [1 0 1]
 [1 1 1]]


In [49]:
weights = np.array([1,1,1])
print(f'weights: {weights}')

weights: [1 1 1]


Step 2: Compute the dot product between the matrix of inputs and weights

In [50]:
dot_products = np.dot(input_table, weights)
print(f'Dot products: {dot_products}')

Dot products: [0 1 2 3]


Step 3: Define the threshold activation function

In [38]:
def  linear_threshold_gate(dot, threshold):
    if dot >= threshold:
        return 1
    else:
        return 0

Step 4: Compute the output based on the threshold value

In [51]:
T = 3
for i in range(0,4):
 activation = linear_threshold_gate(dot_products[i], T)
 print(f'Activation: {activation}')

Activation: 0
Activation: 0
Activation: 0
Activation: 1


McCulloch-Pitts Neural Model for OR case

For OR case, Threshold can be 1 or greater than 1

In [40]:
input_table = np.array([
 [0,0],
 [0,1],
 [1,0],
 [1,1]
])
print(f'Input Table:\n{input_table}')

Input Table:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [41]:
weights = np.array([1,1])
print(f'weights: {weights}')

weights: [1 1]


In [42]:
dot_products = np.dot(input_table, weights)
print(f'Dot products: {dot_products}')

Dot products: [0 1 1 2]


In [43]:
T = 1
for i in range(0,4):
 activation = linear_threshold_gate(dot_products[i], T)
 print(f'Activation: {activation}')

Activation: 0
Activation: 1
Activation: 1
Activation: 1


For NOR case, Threshold will be 0 and weights will be negative

In [44]:
input_table = np.array([
 [0,0],
 [0,1],
 [1,0],
 [1,1]
])
print(f'Input Table:\n{input_table}')

Input Table:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [45]:
weights = np.array([-1,-1])
print(f'weights: {weights}')

weights: [-1 -1]


In [46]:
dot_products = np.dot(input_table, weights)
print(f'Dot products: {dot_products}')

Dot products: [ 0 -1 -1 -2]


In [47]:
T = 0
for i in range(0,4):
 activation = linear_threshold_gate(dot_products[i], T)
 print(f'Activation: {activation}')

Activation: 1
Activation: 0
Activation: 0
Activation: 0
